<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>Receipts.Api</AssemblyName>
    <RootNamespace>Receipts.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Receipts.Application/Receipts.Application.csproj" />
    <ProjectReference Include="../Receipts.Infrastructure/Receipts.Infrastructure.csproj" />
  </ItemGroup>
</Project>
