<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Receipts.Infrastructure</AssemblyName>
    <RootNamespace>Receipts.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Receipts.Domain/Receipts.Domain.csproj" />
    <ProjectReference Include="../Receipts.Application/Receipts.Application.csproj" />
  </ItemGroup>
</Project>
